qawolf:
  image: qawolf/playwright-ci:v0.10.0

  cache:
    paths:
      - /root/.cache/
      - node_modules/

  script:
    - npm install
    # # Start local server
    # - npm run start & npx wait-on http://localhost:3000
    # replace below with command you want to run, example for running a script below
    # - node myScript.js
    - npm test
