pipelines:
  default:
    - step:
        name: Playwright Tests
        image: qawolf/playwright-ci:v0.10.0
        caches:
          - node
          - playwright
        script:
          - npm install
        
          ## Start local server
          # - npm run start & npx wait-on http://localhost:3000
          # replace below with command you want to run, example for running a script below
          # - node myScript.js
          - npm test

definitions:
  caches:
    playwright: ~/.cache